using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace GameHelper.Core.Events
{
    /// <summary>
    /// A first-class event declaration: its name, source, human description and typed fields, plus
    /// the <see cref="Emit"/> method used to publish it. Declaring one per event (in a holder class
    /// like CoreEvents / WarzoneEvents) makes it the single source of truth — the HELPER_STARTED
    /// catalog is generated by reflecting over these, so the docs can never drift from what's emitted.
    /// </summary>
    public sealed class EventDef
    {
        public string Name { get; }
        public string Source { get; }
        public string Description { get; }
        public IReadOnlyList<EventFieldDoc> Fields { get; }

        public EventDef(string name, string source, string description, params EventFieldDoc[] fields)
        {
            Name = name; Source = source; Description = description;
            Fields = fields ?? Array.Empty<EventFieldDoc>();
        }

        /// <summary>Shorthand to declare a payload field.</summary>
        public static EventFieldDoc Field(string name, string type, string description) =>
            new EventFieldDoc(name, type, description);

        /// <summary>Publish this event on the bus, filling its payload.</summary>
        public void Emit(EventBus bus, Action<HelperEvent> fill = null) => bus.Publish(Name, Source, fill);

        public EventDoc ToDoc() => new EventDoc(Name, Source, Description, Fields.ToArray());

        /// <summary>Reflect the public static EventDef fields of the given holder types into docs
        /// (used to build the catalog automatically from the declarations).</summary>
        public static IReadOnlyList<EventDoc> DocsFrom(params Type[] holders)
        {
            var list = new List<EventDoc>();
            foreach (var t in holders)
                foreach (var f in t.GetFields(BindingFlags.Public | BindingFlags.Static))
                    if (f.FieldType == typeof(EventDef) && f.GetValue(null) is EventDef d)
                        list.Add(d.ToDoc());
            return list;
        }
    }
}
